/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BookShop;

import com.microsoft.sqlserver.jdbc.SQLServerException;
import java.awt.Image;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author bolem
 */
public class DatabaseLogin extends javax.swing.JPanel {

    /**
     * Creates new form DatabaseLogin_JPanel
     */
    public DatabaseLogin() {
        initComponents();
        initDisplay();
    }
    
    // To see
    
    /*
     * Initializes components' primary display
     */
    private void initDisplay() {
        // Disables some text fields
        jTextField2.setEnabled(false);
        jTextField3.setEnabled(false);
        jPasswordField1.setEnabled(false);
        
        // Hides check marks
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        
        // Disables login button
        jButton1.setEnabled(false);
        
        // Sets database default image icon
        ImageIcon imageIcon = new ImageIcon("database.default.png"); 
        Image image = imageIcon.getImage(); 
        Image newimg = image.getScaledInstance(128, 128, Image.SCALE_SMOOTH); 
        imageIcon = new ImageIcon(newimg);  
        jLabel5.setIcon(imageIcon);
    }
    
    
    /*
     * Gets a Connection object
     */
    public Connection getConnection() throws SQLServerException {
        // Setting up the DataSource object
        com.microsoft.sqlserver.jdbc.SQLServerDataSource  dataSource 
            = new com.microsoft.sqlserver.jdbc.SQLServerDataSource();
        dataSource.setServerName(jTextField1.getText());
        dataSource.setPortNumber(Integer.parseInt(jTextField2.getText()));
        dataSource.setDatabaseName("BookShop");
        dataSource.setUser(jTextField3.getText());
        dataSource.setPassword(jPasswordField1.getPassword().toString());
        
        return dataSource.getConnection();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Database Login "));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Login Properties"));

        jLabel1.setText("Server Name:");

        jLabel2.setText("Port Number:");

        jLabel3.setText("User Name:");

        jLabel4.setText("Password:");

        jButton1.setText("Set Connection");
        jButton1.setAlignmentY(0.0F);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.setAlignmentY(0.0F);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel6.setText("1");

        jLabel7.setText("2");

        jLabel8.setText("3");

        jLabel9.setText("4");

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPasswordField1, jTextField1, jTextField2, jTextField3});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        // Sets database default image icon
        ImageIcon imageIcon = new ImageIcon("database.file.png");
        Image image = imageIcon.getImage();
        Image newimg = image.getScaledInstance(128, 128,  java.awt.Image.
            SCALE_SMOOTH);
        imageIcon = new ImageIcon(newimg);
        jLabel5.setIcon(imageIcon);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // Tests whether string is null or blank (empty and with white space(s))
        // Also activates and deactivates corresponding check marks
        boolean condition = jTextField1.getText() == null || jTextField1.
            getText().trim().isEmpty();
        boolean incorrect = true;
        while (incorrect) {
            jLabel6.setVisible(false);
            if (condition) {
                jLabel6.setText("\u274C"); // Red Cross Mark Unicode
                jLabel6.setVisible(true);
            } else {
                jLabel6.setText("\u2705"); // Green Heavy Check Mark Unicode
                jLabel6.setVisible(true);
                incorrect = false;
            }
        }
        jTextField2.setEnabled(true);
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // Tests whether string contains digits only
        // Also activates and deactivates corresponding check marks
        boolean incorrect = true;
        while (incorrect) {
            jLabel7.setVisible(false);
            try {
                Integer.parseInt(jTextField2.getText());
                jLabel7.setText("\u2705"); // Green Heavy Check Mark Unicode
                jLabel7.setVisible(true);
                incorrect = false;
            } catch (NumberFormatException ex) {
                System.err.println("Does not contain digits only" + ex.
                    getMessage());
                jLabel7.setText("\u274C"); // Red Cross Mark Unicode
                jLabel7.setVisible(true);
            }            
        }
        jTextField3.setEnabled(true);
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        jLabel8.setText("\u2705"); // Green Heavy Check Mark Unicode
        jLabel8.setVisible(true);
        jPasswordField1.setEnabled(true);
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        jLabel9.setText("\u2705"); // Green Heavy Check Mark Unicode
        jLabel9.setVisible(true);
        jButton1.setEnabled(true);        
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try (Connection connection = getConnection();) {
            // Sets new database image
            ImageIcon imageIcon = new ImageIcon("database.connected.png"); 
            Image image = imageIcon.getImage(); 
            Image newimg = image.getScaledInstance(128, 128, Image.SCALE_SMOOTH); 
            imageIcon = new ImageIcon(newimg);  
            jLabel5.setIcon(imageIcon);
            
            // Saves properties in a file for future use 
            // For use only in case of frequent database ons and offs
            new PrintWriter(new OutputStreamWriter(new FileOutputStream(
                "database.properties.txt"), "UTF-8"), true);
            System.out.print(jTextField1.getText() + " ");
            System.out.print(jTextField2.getText() + " ");
            System.out.print("BookShop ");
            System.out.print(jTextField3.getText() + " "); 
            System.out.println(jPasswordField1.getSelectedText() + " ");
                    
            // Shows modal dialog window
            JOptionPane.showMessageDialog(this, "Database connection has "
                + "succeeded!", "" + connection.getMetaData().
                getDatabaseProductName() + " " + connection.getMetaData().
                getDatabaseProductVersion(), JOptionPane.INFORMATION_MESSAGE);
            
            // Hides panel
            this.setVisible(false);
        } catch (SQLException ex) {
            // Sets new database image
            ImageIcon imageIcon = new ImageIcon("database.notConnected.png"); 
            Image image = imageIcon.getImage(); 
            Image newimg = image.getScaledInstance(128, 128, Image.SCALE_SMOOTH); 
            imageIcon = new ImageIcon(newimg);  
            jLabel5.setIcon(imageIcon);
            
            // Hides modal dialog window
            JOptionPane.showMessageDialog(this, "Database connection has "
                + "failed!", "Connection Error", JOptionPane.ERROR_MESSAGE);
            
            // Sets primary display
            this.setVisible(true);
            initDisplay();
            Logger.getLogger(DatabaseLogin.class.getName()).log(Level.
                SEVERE, null, ex);    
        } catch (FileNotFoundException | UnsupportedEncodingException ex) {
            // Sets primary display
            this.setVisible(true);
            initDisplay();
            Logger.getLogger(DatabaseLogin.class.getName()).log(Level.
                SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
